### PR TITLE
Attempt to update to 1.21

### PR DESCRIPTION
**Pull request by ArduFish**
An attempt to update to 1.21. This only changes the versions, the code will probably need to be updated too.

### CODE REVIEW

**Comment by ZsoltMolnarrr** [comment]
Requires PlayerAnimator 1.21 support.

**Comment by ArduFish** [comment]
https://github.com/KosmX/minecraftPlayerAnimator/pull/91 states that support already exists.

**Comment by ArduFish** [comment]
I managed to build playerAnimator for 1.21 successfully.

**Comment by ThexXTURBOXx** [comment]
I would wait for #402 and rebase this PR in order to avoid having the same issues in 1.21.

**Comment by ZsoltMolnarrr** [comment]
Thank you for all the collaborative effort so far!
I am working to catch up with the game, as it can be seen on git.
The changes will be much more than this PR. :)

**Pull request closed without merging**
