### PR TITLE
Fix NPE

### LINKED ISSUE #368: Conflict With Forge Tiered and Tiered Reforge 1.20.1
**Minecraft version** - 1.20.1
**Mod loader** - Forge 
**Mod version** - 1.8.5-1.20.1
**I am using the latest version available** - For 1.20.1, yes.

**Describe the bug**
When world reaches 100% with Forge's Tiered and Tiered Reforge installed, it immediately crashes with the following error.

<details>
  <summary>Error Messages From Log</summary>
[Server thread/ERROR]: Exception caught during firing event: Cannot invoke "net.minecraft.resources.ResourceLocation.equals(Object)" because "attributeId" is null
	Index: 8
	Listeners:
		0: HIGH
		1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/server/ServerStartedEvent;)V
		2: NORMAL
		3: ASM: org.embeddedt.modernfix.forge.init.ModernFixClientForge@36d3a3e7 onServerStarting(Lnet/minecraftforge/event/server/ServerStartedEvent;)V
		4: net.minecraftforge.eventbus.EventBus$$Lambda$1995/0x0000000800abd6a8@36d9a215
		5: ASM: class dev.shadowsoffire.placebo.util.PlaceboTaskQueue started(Lnet/minecraftforge/event/server/ServerStartedEvent;)V
		6: ASM: class com.cupboard.event.EventHandler serverstart(Lnet/minecraftforge/event/server/ServerStartedEvent;)V
		7: ASM: com.mrcrayfish.framework.event.ForgeEvents@11324488 onServerStarted(Lnet/minecraftforge/event/server/ServerStartedEvent;)V
		8: ASM: class net.bettercombat.forge.events.ForgeEvents onSererStart(Lnet/minecraftforge/event/server/ServerStartedEvent;)V
		9: ASM: class com.momosoftworks.coldsweat.common.event.RegisterChameleonEdibles onWorldLoaded(Lnet/minecraftforge/event/server/ServerStartedEvent;)V
		10: ASM: class com.momosoftworks.coldsweat.common.event.LoadConfigSettings onServerStarted(Lnet/minecraftforge/event/server/ServerStartedEvent;)V
		11: net.minecraftforge.eventbus.EventBus$$Lambda$1995/0x0000000800abd6a8@5e63ffcd
		12: ASM: de.maxhenkel.voicechat.intercompatibility.ForgeCommonCompatibilityManager@36826150 serverStarting(Lnet/minecraftforge/event/server/ServerStartedEvent;)V
		13: ASM: com.natamus.cyclepaintings.forge.events.ForgePaintingEvent@1c9f5cf6 onServerStart(Lnet/minecraftforge/event/server/ServerStartedEvent;)V
		14: LOWEST
		15: ASM: org.embeddedt.modernfix.forge.init.ModernFixForge@4e3d05f8 onServerStarted(Lnet/minecraftforge/event/server/ServerStartedEvent;)V
java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.equals(Object)" because "attributeId" is null
	at TRANSFORMER/bettercombat@1.8.5+1.20.1/net.bettercombat.logic.WeaponAttributesFallback.hasAttributeModifier(WeaponAttributesFallback.java:53)
	at TRANSFORMER/bettercombat@1.8.5+1.20.1/net.bettercombat.logic.WeaponAttributesFallback.initialize(WeaponAttributesFallback.java:24)
	at TRANSFORMER/bettercombat@1.8.5+1.20.1/net.bettercombat.BetterCombat.lambda$onInitialize$0(BetterCombat.java:43)
	at TRANSFORMER/bettercombat@1.8.5+1.20.1/net.bettercombat.forge.events.ForgeEvents.lambda$onSererStart$2(ForgeEvents.java:31)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at TRANSFORMER/bettercombat@1.8.5+1.20.1/net.bettercombat.forge.events.ForgeEvents.onSererStart(ForgeEvents.java:31)
	at TRANSFORMER/bettercombat@1.8.5+1.20.1/net.bettercombat.forge.events.__ForgeEvents_onSererStart_ServerStartedEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.2.0/net.minecraftforge.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:115)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:638)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:833)

[13:58:25] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.equals(Object)" because "attributeId" is null
	at net.bettercombat.logic.WeaponAttributesFallback.hasAttributeModifier(WeaponAttributesFallback.java:53) ~[bettercombat-forge-1.8.5+1.20.1.jar%23499!/:?]
	at net.bettercombat.logic.WeaponAttributesFallback.initialize(WeaponAttributesFallback.java:24) ~[bettercombat-forge-1.8.5+1.20.1.jar%23499!/:?]
	at net.bettercombat.BetterCombat.lambda$onInitialize$0(BetterCombat.java:43) ~[bettercombat-forge-1.8.5+1.20.1.jar%23499!/:?]
	at net.bettercombat.forge.events.ForgeEvents.lambda$onSererStart$2(ForgeEvents.java:31) ~[bettercombat-forge-1.8.5+1.20.1.jar%23499!/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at net.bettercombat.forge.events.ForgeEvents.onSererStart(ForgeEvents.java:31) ~[bettercombat-forge-1.8.5+1.20.1.jar%23499!/:?]
	at net.bettercombat.forge.events.__ForgeEvents_onSererStart_ServerStartedEvent.invoke(.dynamic) ~[bettercombat-forge-1.8.5+1.20.1.jar%23499!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:115) ~[forge-1.20.1-47.2.0-universal.jar%23793!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:638) ~[client-1.20.1-20230612.114412-srg.jar%23788!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23788!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
</details>

**To Reproduce**
1. Install Tiered Reforge, Tiered, and Better Combat in a 1.20.1 environment on forge 47.1.20
2. Launch Game, get to Menu, create world
3. Wait for crash at 100%

**Expected behavior**
I expected these mods would fit beautifully together and compliment the play experience each creates.

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
Fixes #368 
Tested this with BWM: Legacy. After this fix, everything seems to work fine again!

### CODE REVIEW

**Comment by ZsoltMolnarrr** [comment]
I think you are meant to target 1.20.1 branch, right?:)

**Comment by ThexXTURBOXx** [comment]
Oh, yes, of course, thanks :)
However, I can confirm that this problem indeed also affects other branches

**Comment by ZsoltMolnarrr** [comment]
Thank you for the contribution!

**Review by PixelPlates — COMMENTED** [review]
Sorry , begginer at this. How do you moddified ? How can i solve ussing this?

**Pull request merged**
