### PR TITLE
1.19

### PR DESCRIPTION
**Pull request by IMS212**

### CODE REVIEW

**Comment by ZsoltMolnarrr** [comment]
Hello @IMS212 !
I am very grateful for your contribution! This is huge help ❤️
However, I would like to kindly ask for your patience with this merge. 🙏
I am determined to get out a stable version for 1.18.2 as soon as possible. Adding 1.19 compatibility would be too early, because it would hinder my delivery capacity, with the added burden of development, testing, double releasing.

Please join the conversation at https://discord.gg/U67Ws7Pn So we can have a discussion when can we include this.

**Comment by IMS212** [comment]
Done, and no problem! I'll keep it up to date as much as possible in the meantime.

**Review by Skidamek — CHANGES_REQUESTED** [review]
[line 55](https://github.com/ZsoltMolnarrr/BetterCombat/blob/a8dfacbaed99d5e8cf5f586cbac7a918281baff5/src/main/java/net/bettercombat/client/WeaponAttributeTooltip.java#L55) fix:
from:
var handLine = new TranslatableText("item.modifiers.two_handed").formatted(Formatting.GRAY);
to:
var handLine = Text.translatable("item.modifiers.two_handed").formatted(Formatting.GRAY);

**Comment by ZsoltMolnarrr** [comment]
Thanks a lot for this.
1.19 update took a bit more effort than expected, but this PR was great help.

**Pull request closed without merging**
