### PR TITLE
NBT Support

### PR DESCRIPTION
**Pull request by Smartin-b**
This would be a very simple way to allow the parsing of NBT similar to id, using the same registration
This is very crude and propably there is a better way of doing this.

### CODE REVIEW

**Comment by Smartin-b** [comment]
grafik
sadly the modid is needed with this implementation

**Comment by Smartin-b** [comment]
NBT tags arent limited when it comes to \ / and other special characters, so reading them from Filenames isnt a good solution
have sth in mind but that might take some time

**Comment by Smartin-b** [comment]
While this is not working yet the idea is to have a system that doesnt only check for for NBT keys, but can check for ItemId nbt key +value combinations.
This would allow Modders to freely switch animations just by adjusting some basic nbt tags.
Although im kinda regreting it, a simple key detector probably would have been enough, with a similar implementation as in 
https://github.com/ZsoltMolnarrr/BetterCombat/pull/73/commits/abc427b75b4b2c74d006df06506d783a8ab03921
just with a custom line in the json for the tag instead of pulling the filename.

**Comment by ZsoltMolnarrr** [comment]
I am grateful for your motivated contribution, unfortunately I need to reject this PR, for the following reasons:
- Touches much more than it should (theoretically)
- Resolves attributes in an overly complicated way

This is a core feature, I would prefer to implement it myself.

**Comment by Smartin-b** [comment]
Yeah, i can understand that.
The Problem with any NBT implementation is how much of the Tag you want to compare.
While a simple Match for a single key is fast and easy, most of the Mods in questions would greatly benefit
from a complex System that allows any number of Tags to match in Key and if configured also in Value bound to sometimes certain ids, sometimes not.
Im kinda unsure how far the NBT Matching should go.
Maybe the route to go is a simple BetterCombatParent NBT tag to be assigned and force other Mods to comply with that.

**Pull request closed without merging**
