### PR TITLE
Improve Firstperson support, update Loom, update Gradle

### PR DESCRIPTION
**Pull request by tr7zw**
Needed to update the Firstperson dependency, for that loom, and for that gradle 😅 .
The only known issue that needs further resolving on Better Combats end is that the animation doesn't update fast enough during dynamic mode. So when swinging straight and then looking down with dynamic mode, the normal animation finishes before hiding, causing 2 swords.

### CODE REVIEW

**Comment by ZsoltMolnarrr** [comment]
Thank you for the contribution!

**Comment by Angelin01** [comment]
@ZsoltMolnarrr Hi! Sorry to necro this PR. I just cherry picked this commit to the 1.20.1 branch and tested it, it works fine!

<details>
<summary>Pictures with proof</summary>





</details>

Would you mind backporting this fix to the 1.20.1 branch and making a release? It is indeed quite a simple patch. If you prefer, I can open a PR for it, I just can't publish it for you. 1.20.1 seems to be the most popular version before the Mod Loader schism.

<details>
<summary>Patch</summary>

```diff
diff --git a/build.gradle b/build.gradle
index 367e73c..f4e6a55 100755
--- a/build.gradle
+++ b/build.gradle
@@ -6,7 +6,7 @@ buildscript {

 plugins {
     id "architectury-plugin" version "3.4-SNAPSHOT"
-    id "dev.architectury.loom" version "1.4-SNAPSHOT" apply false
+    id "dev.architectury.loom" version "1.6-SNAPSHOT" apply false
     id "org.cadixdev.licenser" version "0.6.1"
     id "io.github.juuxel.loom-quiltflower" version "1.7.+" apply false
     id "me.shedaniel.unified-publishing" version "0.1.+" apply false
@@ -53,4 +53,4 @@ allprojects {

 ext.changelog_last_section = { ->
     return new File("CHANGELOG.md").text.split('\n# ')[0]
-}
\ No newline at end of file
+}
diff --git a/common/src/main/java/net/bettercombat/compatibility/FirstPersonModelHelper.java b/common/src/main/java/net/bettercombat/compatibility/FirstPersonModelHelper.java
index fbf5f40..9c4f8d4 100644
--- a/common/src/main/java/net/bettercombat/compatibility/FirstPersonModelHelper.java
+++ b/common/src/main/java/net/bettercombat/compatibility/FirstPersonModelHelper.java
@@ -1,13 +1,14 @@
 package net.bettercombat.compatibility;

 import dev.tr7zw.firstperson.api.FirstPersonAPI;
+import dev.tr7zw.firstperson.FirstPersonModelCore;

 import java.util.function.Supplier;

 public class FirstPersonModelHelper {
     public static Supplier<Boolean> isDisabled() {
         return (() -> {
-            return !FirstPersonAPI.isEnabled();
+            return !(FirstPersonAPI.isEnabled() && !FirstPersonModelCore.instance.getLogicHandler().hideArmsAndItems());
         });
     }
 }
diff --git a/gradle.properties b/gradle.properties
index 4d58b4c..e0085d1 100755
--- a/gradle.properties
+++ b/gradle.properties
@@ -27,6 +27,6 @@ tiny_config_version=2.3.2
 # Compatibility
 mod_menu_version=7.0.1
 #https://modrinth.com/mod/first-person-model/version/evkvoubL = 2.2.3-1.20
-fpm_version=evkvoubL
-spell_engine_version=0.12.0+1.20.1
-mixin_extras_version=0.2.0
\ No newline at end of file
+fpm_version=jD6JfmfQ
+spell_engine_version=0.12.5+1.20.1
+mixin_extras_version=0.3.5
diff --git a/gradle/wrapper/gradle-wrapper.properties b/gradle/wrapper/gradle-wrapper.properties
index db9a6b8..17655d0 100755
--- a/gradle/wrapper/gradle-wrapper.properties
+++ b/gradle/wrapper/gradle-wrapper.properties
@@ -1,5 +1,5 @@
 distributionBase=GRADLE_USER_HOME
 distributionPath=wrapper/dists
-distributionUrl=https\://services.gradle.org/distributions/gradle-8.3-bin.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-8.6-bin.zip
 zipStoreBase=GRADLE_USER_HOME
 zipStorePath=wrapper/dists
```
</details>

(Also, as a side note, I noticed a few commits (15bf9fb6d75e5b2926f4ff3204e0133546f3f6a7 and https://github.com/ZsoltMolnarrr/BetterCombat/commit/538e2b0efa664eea8825dc85cc730563630ac2a4) related to networking that aren't in the 1.20.1 branch, should those be backported as well? I can try to cherry-pick them too).

**Comment by Okcra** [comment]
@Angelin01 Hello, great thinking applying this commit to the older version!
I am attempting to patch this into my 1.20.1 modpack but as a complete beginner with no experience I'm having trouble figuring out how - any chance you could explain the process?

**Comment by Angelin01** [comment]
> @Angelin01 Hello, great thinking applying this commit to the older version! I am attempting to patch this into my 1.20.1 modpack but as a complete beginner with no experience I'm having trouble figuring out how - any chance you could explain the process?

Hi, do you have any Java development experience? If so, it is deadly simple, just clone the branch for 1.20.1, apply my patch using some git commands and build the new jar with some gradle commands.

If you don't, then this might be a bit too complex, then it's best to try and get Zsolt to actually patch the 1.20.1 version.

Note that if you are distributing this modpack, you can freely distribute the modified jar for the 1.20.1 version, as long as you comply with the [GPLv3 license](https://github.com/ZsoltMolnarrr/BetterCombat/blob/1.20.1/LICENSE).

**Comment by Okcra** [comment]
@Angelin01 After trying for a few hours I've had no luck, I think I'm a bit out of my depth with this one! Thank you for your response anyway, hopefully Zsolt will backport these fixes soon

**Pull request merged**
