### PR TITLE
Update ja_jp.json

### PR DESCRIPTION
**Pull request by EndilCrafter**

### CODE REVIEW

**Comment by ZsoltMolnarrr** [comment]
Could you clarify how these translations will be more accurate?
Also please make sure all new values are translated too.

**Comment by EndilCrafter** [comment]
I'm not good at English so I cannot perfectly understand what you say.
・some passage makes more formal　[…する→…します]
・add period　[。]
・some translations(such as literal translations) makes more natural
・some fix　[フレーム　レート→フレームレート]

**Comment by ZsoltMolnarrr** [comment]
There are untranslated entries. Could you translate those too?
```
  "text.autoconfig.bettercombat.option.client.mineWithWeaponBlacklist" : "Mine with weapon blacklist",
  "text.autoconfig.bettercombat.option.client.mineWithWeaponBlacklist.@Tooltip" : "Weapons with an ID that matches this regex will never be used to harvest blocks",
```

**Comment by ZsoltMolnarrr** [comment]
Thank you for the contribution!

**Pull request merged**
